# Generated by Django 2.2.1 on 2019-06-11 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_user_has_confirmed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['c_time'], 'verbose_name': '注册用户', 'verbose_name_plural': '注册用户'},
        ),
    ]
