# Generated by Django 2.2.1 on 2019-06-07 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
