# Generated by Django 2.2.1 on 2019-06-11 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
